<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DSAN 5000 - Data Cleaning</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./data_cleaning.html">Data Cleaning</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">DSAN 5000</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About You</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./code.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Code</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_gathering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Gathering</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_cleaning.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Data Cleaning</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_exploration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Exploration</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Clustering</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dimensionality_reduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dimensionality Reduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decision_trees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Decision Trees</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./arm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ARM</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conclusions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conclusions</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#cleaning-process" id="toc-cleaning-process" class="nav-link active" data-scroll-target="#cleaning-process">Cleaning Process</a>
  <ul class="collapse">
  <li><a href="#th-down-data" id="toc-th-down-data" class="nav-link" data-scroll-target="#th-down-data">4th Down Data</a>
  <ul class="collapse">
  <li><a href="#by-coach" id="toc-by-coach" class="nav-link" data-scroll-target="#by-coach">By Coach</a></li>
  <li><a href="#by-situation" id="toc-by-situation" class="nav-link" data-scroll-target="#by-situation">By Situation</a></li>
  </ul></li>
  <li><a href="#sentiment-analysis" id="toc-sentiment-analysis" class="nav-link" data-scroll-target="#sentiment-analysis">Sentiment Analysis</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Data Cleaning</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="cleaning-process" class="level1">
<h1>Cleaning Process</h1>
<section id="th-down-data" class="level2">
<h2 class="anchored" data-anchor-id="th-down-data">4th Down Data</h2>
<section id="by-coach" class="level3">
<h3 class="anchored" data-anchor-id="by-coach">By Coach</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(raw_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 383
  play_id game_id      old_game_id home_team away_team season_type  week posteam
    &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt;       &lt;chr&gt;     &lt;chr&gt;     &lt;chr&gt;       &lt;int&gt; &lt;chr&gt;  
1       1 2022_01_BAL… 2022091107  NYJ       BAL       REG             1 &lt;NA&gt;   
2      43 2022_01_BAL… 2022091107  NYJ       BAL       REG             1 NYJ    
3      68 2022_01_BAL… 2022091107  NYJ       BAL       REG             1 NYJ    
4      89 2022_01_BAL… 2022091107  NYJ       BAL       REG             1 NYJ    
5     115 2022_01_BAL… 2022091107  NYJ       BAL       REG             1 NYJ    
6     136 2022_01_BAL… 2022091107  NYJ       BAL       REG             1 NYJ    
# ℹ 375 more variables: posteam_type &lt;chr&gt;, defteam &lt;chr&gt;, side_of_field &lt;chr&gt;,
#   yardline_100 &lt;dbl&gt;, game_date &lt;chr&gt;, quarter_seconds_remaining &lt;dbl&gt;,
#   half_seconds_remaining &lt;dbl&gt;, game_seconds_remaining &lt;dbl&gt;,
#   game_half &lt;chr&gt;, quarter_end &lt;dbl&gt;, drive &lt;dbl&gt;, sp &lt;dbl&gt;, qtr &lt;dbl&gt;,
#   down &lt;dbl&gt;, goal_to_go &lt;dbl&gt;, time &lt;chr&gt;, yrdln &lt;chr&gt;, ydstogo &lt;dbl&gt;,
#   ydsnet &lt;dbl&gt;, desc &lt;chr&gt;, play_type &lt;chr&gt;, yards_gained &lt;dbl&gt;,
#   shotgun &lt;dbl&gt;, no_huddle &lt;dbl&gt;, qb_dropback &lt;dbl&gt;, qb_kneel &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>There are a large number of columns in this data, taken from the 2022 NFL season, we do not need all 383. The purpose of this data is to help determine how coaches today approach 4th down, a basic yet essential decision in the NFL. To do this we only need to look at these columns:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>fourth_downs <span class="ot">&lt;-</span> raw_data <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(go_boost) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(go)) <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(home_coach, away_coach, posteam_type, ydstogo, yardline_100, posteam, go_boost, go, epa)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(fourth_downs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  home_coach away_coach posteam_type ydstogo yardline_100 posteam go_boost    go
  &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt;        &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt;
1 Robert Sa… John Harb… home              15           64 NYJ       -3.45      0
2 Robert Sa… John Harb… away               1           51 BAL        3.67      0
3 Robert Sa… John Harb… home               9           82 NYJ       -2.07      0
4 Robert Sa… John Harb… away               9           65 BAL       -1.01      0
5 Robert Sa… John Harb… away               3            6 BAL        0.141     0
6 Robert Sa… John Harb… home               1           66 NYJ        0.654     0
# ℹ 1 more variable: epa &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Each unit in this table is one 4th down decision. The variables include:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">home_coach</td>
<td style="text-align: left;">Home Team Coach</td>
</tr>
<tr class="even">
<td style="text-align: left;">away_coach</td>
<td style="text-align: left;">Away Team Coach</td>
</tr>
<tr class="odd">
<td style="text-align: left;">posteam_type</td>
<td style="text-align: left;">Offense Home or Away</td>
</tr>
<tr class="even">
<td style="text-align: left;">ydstogo</td>
<td style="text-align: left;">Yards to Go</td>
</tr>
<tr class="odd">
<td style="text-align: left;">yardline_100</td>
<td style="text-align: left;">Yardline Relative to End Zone</td>
</tr>
<tr class="even">
<td style="text-align: left;">posteam</td>
<td style="text-align: left;">Offense Team</td>
</tr>
<tr class="odd">
<td style="text-align: left;">go_boost</td>
<td style="text-align: left;">Change in Win Probability if Conversion Attempted</td>
</tr>
<tr class="even">
<td style="text-align: left;">go</td>
<td style="text-align: left;">Conversion Attempted (T/F)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">epa</td>
<td style="text-align: left;">Estimated Points Added as a Result of the Play</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Making a table showing when coaches make the correct decisions on 4th down is essential in evaluating their decision making process. This is made easy by the inclusion of the <code>go_boost</code> variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>fourth_decisions <span class="ot">&lt;-</span> fourth_downs <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">should_go =</span> <span class="fu">ifelse</span>((go_boost <span class="sc">&gt;</span> <span class="dv">0</span>),</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                             (<span class="fu">if_else</span>(go <span class="sc">==</span> <span class="dv">100</span>, <span class="dv">1</span>, <span class="dv">0</span>)),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                             <span class="cn">NA</span>),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">shouldnt_go =</span> <span class="fu">ifelse</span>((go_boost <span class="sc">&lt;</span> <span class="dv">0</span>),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>                             (<span class="fu">if_else</span>(go <span class="sc">==</span> <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>)),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>                             <span class="cn">NA</span>),</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">coach =</span> <span class="fu">if_else</span>(posteam_type <span class="sc">==</span> <span class="st">"home"</span>, home_coach, away_coach),) <span class="sc">%&gt;%</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(coach, ydstogo, yardline_100, go_boost, should_go, shouldnt_go, go, epa) <span class="sc">%&gt;%</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(coach) <span class="sc">%&gt;%</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">should_go =</span> </span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>                <span class="fu">sum</span>(should_go <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> </span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>                (<span class="fu">sum</span>(should_go <span class="sc">==</span> <span class="dv">0</span> <span class="sc">|</span> should_go <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>              <span class="at">shouldnt_go =</span> </span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>                <span class="fu">sum</span>(shouldnt_go <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> </span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>                (<span class="fu">sum</span>(shouldnt_go <span class="sc">==</span> <span class="dv">0</span> <span class="sc">|</span> shouldnt_go <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>              <span class="at">EPA =</span> <span class="fu">mean</span>(epa),</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>              <span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(count <span class="sc">&gt;</span> <span class="dv">50</span>)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(fourth_decisions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  coach          should_go shouldnt_go      EPA count
  &lt;chr&gt;              &lt;dbl&gt;       &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;
1 Andy Reid          0.216       0.982  0.0590    106
2 Arthur Smith       0.333       0.985 -0.0540    114
3 Bill Belichick     0.204       0.962 -0.221     128
4 Brandon Staley     0.347       0.971 -0.00908   140
5 Brian Daboll       0.361       0.949  0.159     139
6 Dan Campbell       0.507       0.907 -0.00432   121</code></pre>
</div>
</div>
<p>This data shows when coaches make the correct choice on 4th down, their average estimated points added on 4th downs throughout the season, and the number of 4th down decisions they had to make throughout the season. It shows the percent of times each coach makes the correct decision in two scenarios: when going for it would have a positive effect on their win probability and when going for it would have a negative effect on their win probability.</p>
</section>
<section id="by-situation" class="level3">
<h3 class="anchored" data-anchor-id="by-situation">By Situation</h3>
<p>One of, if not the most important factor in making a decision on fourth down is the position your team is on the field. Looking at this more closely requires a table that shows coaches decisions based on where they are on the field and how many downs they need to gain to get a first down.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>fourth_position <span class="ot">&lt;-</span> fourth_downs <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">should_go =</span> <span class="fu">ifelse</span>((go_boost <span class="sc">&gt;</span> <span class="dv">0</span>),</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                             (<span class="fu">if_else</span>(go <span class="sc">==</span> <span class="dv">100</span>, <span class="dv">1</span>, <span class="dv">0</span>)),</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>                             <span class="cn">NA</span>),</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">shouldnt_go =</span> <span class="fu">ifelse</span>((go_boost <span class="sc">&lt;</span> <span class="dv">0</span>),</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>                             (<span class="fu">if_else</span>(go <span class="sc">==</span> <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>)),</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>                             <span class="cn">NA</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(yardline_100,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>         ydstogo,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>         go,</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>         go_boost,</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>         should_go,</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>         shouldnt_go) <span class="sc">%&gt;%</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(yardline_100, ydstogo) <span class="sc">%&gt;%</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">go =</span> <span class="fu">mean</span>(go),</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>            <span class="at">count =</span> <span class="fu">n</span>(),</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>            <span class="at">go_boost =</span> <span class="fu">mean</span>(go_boost)) <span class="sc">%&gt;%</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(go_boost <span class="sc">&gt;</span> <span class="sc">-</span><span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'yardline_100'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(fourth_position)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
# Groups:   yardline_100 [3]
  yardline_100 ydstogo    go count go_boost
         &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt;
1            1       1  80.5    41    7.06 
2            2       1  75       4    3.69 
3            2       2  40.7    27    2.89 
4            3       1  50       2    2.54 
5            3       2  16.7     6    0.995
6            3       3  38.5    26    0.721</code></pre>
</div>
</div>
<p>This table shows us the percentage of times a coach chose to go for it in the given situation. The first row, for example, shows that 80.5% of the time a coach decided to go for it when they were at 4th and 1 at the 1 yard line - they were 1 yard away from scoring. It also shows is the average increase in win probability if a coach were to go for it. For example, at 4th and 1 at the 1 yard line, going for it increases your win probability by an average of 7%, an incredibly large number.</p>
</section>
</section>
<section id="sentiment-analysis" class="level2">
<h2 class="anchored" data-anchor-id="sentiment-analysis">Sentiment Analysis</h2>
<p>The NFL subreddit is a useful place to extract text data produced by fans and their reaction to these essential decisions. Like most jobs, the goal of an NFL head coach is not only to win games, but to keep their bosses happy. The size and outspoken nature of NFL fan bases can be a factor in the job security of these coaches, as if a coach loses the fans, their job gets a lot harder. This is where sentiment analysis comes in, as getting an idea of how fans feel about 4th down decisions by certain coaches may give us insights into how they are making their decisions, and whether or not the fans have any influence on the decision making process.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> praw</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.feature_extraction.text <span class="im">import</span> CountVectorizer</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>reddit <span class="op">=</span> praw.Reddit(<span class="st">"bot1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This allows us to get posts from the NFL subreddit using a search query of “4th down” and access the comments of those posts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>subreddit <span class="op">=</span> reddit.subreddit(<span class="st">"nfl"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>query <span class="op">=</span> <span class="st">"4th down"</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>top_posts <span class="op">=</span> subreddit.search(query, limit<span class="op">=</span><span class="dv">100</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>urls <span class="op">=</span> []</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>corpus <span class="op">=</span> []</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> post <span class="kw">in</span> top_posts:</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    urls.append(post.permalink)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>url <span class="op">=</span> <span class="st">"https://www.reddit.com"</span> <span class="op">+</span> urls[<span class="dv">0</span>]</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>submission <span class="op">=</span> reddit.submission(url<span class="op">=</span>url)</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>submission.comments.replace_more(limit<span class="op">=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[&lt;MoreComments count=338, children=['g86rob4', 'g86w9sz', 'g86spfe', '...']&gt;, &lt;MoreComments count=50, children=['g86u1l0']&gt;, &lt;MoreComments count=22, children=['g87nr1u', 'g86u185']&gt;, &lt;MoreComments count=19, children=['g8746y9', 'g875lus']&gt;, &lt;MoreComments count=17, children=['g86our5']&gt;, &lt;MoreComments count=12, children=['g86ntis', 'g86pv9c', 'g86vsmi', '...']&gt;, &lt;MoreComments count=12, children=['g86tjz0', 'g88dxu3', 'g874r37', '...']&gt;, &lt;MoreComments count=10, children=['g86upwx', 'g86ultp']&gt;, &lt;MoreComments count=9, children=['g87k13x', 'g86o1j9', 'g87wsxf']&gt;, &lt;MoreComments count=8, children=['g86u97z', 'g86obcw', 'g86xpy6', '...']&gt;, &lt;MoreComments count=8, children=['g87c49d', 'g86ugsz', 'g877p0k', '...']&gt;, &lt;MoreComments count=7, children=['g877imq', 'g87kh7l', 'g89p26w', '...']&gt;, &lt;MoreComments count=7, children=['g88bvze', 'g87ku3m', 'g87nw1x', 'g872v4n']&gt;, &lt;MoreComments count=7, children=['g86x048', 'g87hqcz', 'g88a3uy', '...']&gt;, &lt;MoreComments count=7, children=['g87zpc7', 'g871cu5']&gt;, &lt;MoreComments count=7, children=['g86oxbu']&gt;, &lt;MoreComments count=6, children=['g87wwd7', 'g87wwjc', 'g86vugx', '...']&gt;, &lt;MoreComments count=6, children=['g86pq3e', 'g86qf9e']&gt;, &lt;MoreComments count=6, children=['g87vm0k', 'g86pf8w', 'g86pfpz', '...']&gt;, &lt;MoreComments count=6, children=['g86x90t', 'g87kfqf', 'g873sjz', '...']&gt;, &lt;MoreComments count=6, children=['g86oe3o', 'g87wg6e', 'g89gr1j', '...']&gt;, &lt;MoreComments count=6, children=['g86nunf', 'g86p8ze', 'g86pwzt']&gt;, &lt;MoreComments count=5, children=['g87om4z', 'g879zcg', 'g89bpxg', '...']&gt;, &lt;MoreComments count=5, children=['g875x3g', 'g87wek1', 'g88cq9i', 'g87he5o']&gt;, &lt;MoreComments count=5, children=['g86pm76', 'g86oovd', 'g86q9m2', 'g86qref']&gt;, &lt;MoreComments count=5, children=['g86qv3t', 'g86p7g9']&gt;, &lt;MoreComments count=5, children=['g86mmlt']&gt;, &lt;MoreComments count=5, children=['g86rchy', 'g86pjic', 'g880745', '...']&gt;, &lt;MoreComments count=4, children=['g87ew8h', 'g87k6p8', 'g87jhql']&gt;, &lt;MoreComments count=4, children=['g87ytxi', 'g880kl5', 'g894n3r', 'g87hy0v']&gt;, &lt;MoreComments count=4, children=['g87nonn']&gt;, &lt;MoreComments count=4, children=['g86nwop', 'g87ow5j', 'g87qauz', 'g87vmct']&gt;, &lt;MoreComments count=4, children=['g87wp4y', 'g89huil', 'g87rk8a', 'g87lg55']&gt;, &lt;MoreComments count=4, children=['g86mpf7']&gt;, &lt;MoreComments count=4, children=['g86oeio']&gt;, &lt;MoreComments count=4, children=['g874vc3', 'g8e3loc', 'g886pd3', 'g88dkoi']&gt;, &lt;MoreComments count=4, children=['g86ogod', 'g87qjnp', 'g872n2e', 'g876gqt']&gt;, &lt;MoreComments count=4, children=['g86ukn3', 'g87d9kl', 'g87oqnq', 'g87ysi7']&gt;, &lt;MoreComments count=3, children=['g879prv']&gt;, &lt;MoreComments count=3, children=['g86zsko', 'g88axm6', 'g86q1s4']&gt;, &lt;MoreComments count=3, children=['g86pay4', 'g87otas', 'g87k6sg']&gt;, &lt;MoreComments count=3, children=['g86yhep', 'g86ygl3']&gt;, &lt;MoreComments count=3, children=['g87olne', 'g8929l8', 'g86o40j']&gt;, &lt;MoreComments count=3, children=['g86xw1q']&gt;, &lt;MoreComments count=3, children=['g871pb4', 'g86y4mx']&gt;, &lt;MoreComments count=3, children=['g87zu94', 'g86pv9z', 'g879cof']&gt;, &lt;MoreComments count=3, children=['g86xjh8', 'g86pzw1']&gt;, &lt;MoreComments count=3, children=['g86sf6e', 'g86mh2g', 'g86my9d']&gt;, &lt;MoreComments count=2, children=['g874wl8']&gt;, &lt;MoreComments count=2, children=['g870t7q', 'g885p2g']&gt;, &lt;MoreComments count=2, children=['g87wk8t', 'g88y0jc']&gt;, &lt;MoreComments count=2, children=['g86r7n9']&gt;, &lt;MoreComments count=2, children=['g8704vj', 'g87mtxl']&gt;, &lt;MoreComments count=2, children=['g87b3xf']&gt;, &lt;MoreComments count=2, children=['g87e6hp', 'g888azh']&gt;, &lt;MoreComments count=2, children=['g86tpwq', 'g878ucd']&gt;, &lt;MoreComments count=2, children=['g87nw3t', 'g86obxo']&gt;, &lt;MoreComments count=2, children=['g87y03d']&gt;, &lt;MoreComments count=2, children=['g89c4g3', 'g87uem0']&gt;, &lt;MoreComments count=2, children=['g87fyi2']&gt;, &lt;MoreComments count=2, children=['g87phtp', 'g88c7wy']&gt;, &lt;MoreComments count=2, children=['g86qmwx', 'g899flo']&gt;, &lt;MoreComments count=2, children=['g87v13k', 'g87nnlw']&gt;, &lt;MoreComments count=2, children=['g87t7tm']&gt;, &lt;MoreComments count=2, children=['g86ox5p', 'g86owzs']&gt;, &lt;MoreComments count=2, children=['g895s2u', 'g86siam']&gt;, &lt;MoreComments count=2, children=['g8akn8y', 'g88efwp']&gt;, &lt;MoreComments count=2, children=['g87k42o']&gt;, &lt;MoreComments count=2, children=['g87ngmh']&gt;, &lt;MoreComments count=2, children=['g87zz7b', 'g88cu86']&gt;, &lt;MoreComments count=2, children=['g86pqwz', 'g870n6c']&gt;, &lt;MoreComments count=2, children=['g86n2n2', 'g86n6w9']&gt;, &lt;MoreComments count=2, children=['g879n3n', 'g86p3iv']&gt;, &lt;MoreComments count=2, children=['g87n2tn']&gt;, &lt;MoreComments count=2, children=['g86p2uz']&gt;, &lt;MoreComments count=1, children=['g87jw2s']&gt;, &lt;MoreComments count=1, children=['g87o0ww']&gt;, &lt;MoreComments count=1, children=['g8859tg']&gt;, &lt;MoreComments count=1, children=['g87lb0g']&gt;, &lt;MoreComments count=1, children=['g86o3mx']&gt;, &lt;MoreComments count=1, children=['g89g34g']&gt;, &lt;MoreComments count=1, children=['g8951hu']&gt;, &lt;MoreComments count=1, children=['g8e306j']&gt;, &lt;MoreComments count=1, children=['g870ebz']&gt;, &lt;MoreComments count=1, children=['g87jzm1']&gt;, &lt;MoreComments count=1, children=['g86sm53']&gt;, &lt;MoreComments count=1, children=['g87ciya']&gt;, &lt;MoreComments count=1, children=['g86t4m1']&gt;, &lt;MoreComments count=1, children=['g8848rf']&gt;, &lt;MoreComments count=1, children=['g86qsx2']&gt;, &lt;MoreComments count=1, children=['g8756qe']&gt;, &lt;MoreComments count=1, children=['g87sc6e']&gt;, &lt;MoreComments count=1, children=['g874mh9']&gt;, &lt;MoreComments count=1, children=['g86ohna']&gt;, &lt;MoreComments count=1, children=['g87gnx5']&gt;, &lt;MoreComments count=1, children=['g87u15i']&gt;, &lt;MoreComments count=1, children=['g87jhuj']&gt;, &lt;MoreComments count=1, children=['g87wmzv']&gt;, &lt;MoreComments count=1, children=['g875ryb']&gt;, &lt;MoreComments count=1, children=['g87jnpo']&gt;, &lt;MoreComments count=1, children=['g86pl6b']&gt;, &lt;MoreComments count=1, children=['g87a5bk']&gt;, &lt;MoreComments count=1, children=['g86t5fr']&gt;, &lt;MoreComments count=1, children=['g88b1v8']&gt;, &lt;MoreComments count=1, children=['g87kqr0']&gt;, &lt;MoreComments count=1, children=['g8aa339']&gt;, &lt;MoreComments count=1, children=['g86r39d']&gt;, &lt;MoreComments count=1, children=['g89g68w']&gt;, &lt;MoreComments count=1, children=['g86p7hq']&gt;, &lt;MoreComments count=1, children=['g881vl7']&gt;, &lt;MoreComments count=1, children=['g88i16j']&gt;, &lt;MoreComments count=1, children=['g8a1lbd']&gt;, &lt;MoreComments count=1, children=['g88hgq4']&gt;, &lt;MoreComments count=1, children=['g88ukf7']&gt;, &lt;MoreComments count=1, children=['g87eizr']&gt;, &lt;MoreComments count=1, children=['g87itku']&gt;, &lt;MoreComments count=1, children=['g88485u']&gt;, &lt;MoreComments count=1, children=['g87k178']&gt;, &lt;MoreComments count=1, children=['g881pf9']&gt;, &lt;MoreComments count=1, children=['g86u0y6']&gt;, &lt;MoreComments count=1, children=['g88wwdf']&gt;, &lt;MoreComments count=1, children=['g86odkd']&gt;, &lt;MoreComments count=1, children=['g88y2nq']&gt;, &lt;MoreComments count=1, children=['g87xzn3']&gt;, &lt;MoreComments count=1, children=['g87xclj']&gt;, &lt;MoreComments count=1, children=['g880q35']&gt;, &lt;MoreComments count=1, children=['g88rs81']&gt;, &lt;MoreComments count=1, children=['g883f06']&gt;, &lt;MoreComments count=1, children=['g88xnri']&gt;, &lt;MoreComments count=1, children=['g86qy7i']&gt;, &lt;MoreComments count=1, children=['g88j9de']&gt;, &lt;MoreComments count=1, children=['g87diha']&gt;, &lt;MoreComments count=1, children=['g87ee9l']&gt;, &lt;MoreComments count=1, children=['g86p0yh']&gt;, &lt;MoreComments count=1, children=['g87fesb']&gt;, &lt;MoreComments count=1, children=['g87yg5m']&gt;, &lt;MoreComments count=1, children=['g874k32']&gt;, &lt;MoreComments count=1, children=['g88qa51']&gt;, &lt;MoreComments count=1, children=['g89fx4d']&gt;, &lt;MoreComments count=1, children=['g88hrnr']&gt;, &lt;MoreComments count=1, children=['g8849qs']&gt;, &lt;MoreComments count=0, children=[]&gt;, &lt;MoreComments count=0, children=[]&gt;]</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> top_level_comment <span class="kw">in</span> submission.comments:</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    corpus.append(top_level_comment.body)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>vectorizer<span class="op">=</span>CountVectorizer()</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>Xs <span class="op">=</span> vectorizer.fit_transform(corpus)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>col_names<span class="op">=</span>vectorizer.get_feature_names_out()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The overall sentiment from this brief analysis is a positive one, but the search terms need to be more specific to get any useful information out of this process.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> nltk.sentiment <span class="im">import</span> SentimentIntensityAnalyzer</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>overall <span class="op">=</span> []</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>sia <span class="op">=</span> SentimentIntensityAnalyzer()</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> text <span class="kw">in</span> corpus:</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  score<span class="op">=</span>sia.polarity_scores(text)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  overall.append(score[<span class="st">'compound'</span>])</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="bu">sum</span>(overall)<span class="op">/</span><span class="bu">len</span>(overall)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.03216993006993008</code></pre>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>