project:
  type: website

website:
  title: "4th Down Decision Making"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - data_gathering.qmd
      - data_cleaning1.qmd
      - section: "Data Exploration"
        contents:
        - fourth_decisions.qmd
        - high_leverage_scenarios.qmd
        - effect_on_coach_success.qmd
      - section: "Naïve Bayes"
        contents:
        - naive_bayes.qmd
        - feature_record.qmd
        - feature_text.qmd
      - coach_clustering.qmd
      - dimensionality_reduction.qmd
      - section: "Decision Trees"
        contents:
        - decision_trees.ipynb
        - random_forests.ipynb
      - conclusions.qmd
      - about.qmd
      - code.qmd
      - data.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    fontsize: 1em

editor: visual

