project:
  type: website

website:
  title: "DSAN 5000"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - data_gathering.qmd
      - section: "Data Cleaning"
        contents:
        - data_cleaning1.qmd
        - data_cleaning2.qmd
      - section: "Data Exploration"
        contents:
        - fourth_decisions.qmd
        - high_leverage_scenarios.qmd
        - effect_on_coach_success.qmd
      - section: "Naïve Bayes"
        contents:
        - naive_bayes.qmd
        - feature_record.qmd
        - feature_text.qmd
      - clustering.qmd
      - dimensionality_reduction.qmd
      - decision_trees.qmd
      - arm.qmd
      - conclusions.qmd
      - about.qmd
      - code.qmd
      - data.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    fontsize: 1em

editor: visual

