project:
  type: website

website:
  title: "dsan5000"
  navbar:
    left:
      - href: about.qmd
        text: About You
      - code.qmd
      - data.qmd
      - introduction.qmd
      - data_gathering.qmd
      - data_cleaning.qmd
      - data_exploration.qmd
      - clustering.qmd
      - dimensionality_reduction.qmd
      - decision_trees.qmd
      - arm.qmd
      - conclusions.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

