---
title: "Effect on Team Success"
editor_options: 
  chunk_output_type: inline
bibliography: references.bib
---

```{r setup, include = FALSE}
library(nflverse)
library(tidyverse)
library(ggplot2)
library(grid)
library(reticulate)
library(kableExtra)
library(gridExtra)
library(plotly)
library(RColorBrewer)
library(scales)
options(digits = 3)

load("clean_data.Rdata")
```

We would like to look at at the effect 4th down decision making has on team success. A simple measure of team success season by season is how many wins a team had. To take a quick look this, we can create a cross-tabulation showing what correct decision rate on 4th down looks like compared to the amount of wins a team had. Wins data from profootballreference.com. 

```{r team_wins, include = FALSE}
ARI <- c(11, 13, 7, 8, 3, 5, 8, 11, 4)
ATL <- c(6, 8, 11, 10, 7, 7, 4, 7, 7)  
BAL <- c(10, 5, 8, 9, 10, 14, 11, 8, 10)  
BUF <- c(9, 8, 7, 9, 6, 10, 13, 11, 13)  
CAR <- c(7, 15, 6, 11, 7, 5, 5, 5, 7)  
CHI <- c(5, 6, 3, 5, 12, 8, 8, 6, 3)  
CIN <- c(10, 12, 6, 7, 6, 2, 4, 10, 12)  
CLE <- c(7, 3, 1, 0, 7, 6, 11, 8, 7)  
DAL <- c(12, 4, 13, 9, 10, 8, 6, 12, 12)  
DEN <- c(12, 12, 9, 5, 6, 7, 5, 7, 5)  
DET <- c(11, 7, 9, 9, 6, 3, 5, 3, 9)  
GB <- c(12, 10, 10, 7, 6, 13, 13, 13, 8)  
HOU <- c(9, 9, 9, 4, 11, 10, 4, 4, 3)  
IND <- c(11, 8, 8, 4, 10, 7, 11, 9, 4)  
JAX <- c(3, 5, 3, 10, 5, 6, 1, 3, 9)  
KC <- c(9, 11, 12, 10, 12, 12, 14, 12, 14)
LA <- c(6, 7, 4, 11, 13, 9, 10, 12, 5)
LAC <- c(9, 4, 5, 9, 12, 5, 7, 9, 10)  
LV <- c(3, 7, 12, 6, 4, 7, 8, 10, 6)  
MIA <- c(8, 6, 10, 6, 7, 5, 10, 9, 9)  
MIN <- c(7, 11, 8, 13, 8, 10, 7, 8, 13)  
NE <- c(12, 12, 14, 13, 11, 12, 7, 10, 8)  
NO <- c(7, 7, 7, 11, 13, 13, 12, 9, 7)  
NYG <- c(6, 6, 11, 3, 5, 4, 6, 4, 9)  
NYJ <- c(4, 10, 5, 5, 4, 7, 2, 4, 7)  
PHI <- c(10, 7, 7, 13, 9, 9, 4, 9, 14)  
PIT <- c(11, 10, 11, 13, 9, 8, 12, 9, 9)  
SEA <- c(8, 5, 2, 6, 4, 13, 6, 10, 13)  
SF <- c(12, 10, 10, 9, 10, 11, 12, 7, 9)
TB <- c(2, 6, 9, 5, 5, 7, 11, 13, 8)  
TEN <- c(2, 3, 9, 9, 9, 9, 11, 12, 7)  
WAS <- c(4, 9, 8, 7, 7, 3, 7, 7, 8)  
```


```{r add_wins, include = FALSE}
filtered <- fourth_decisions %>% 
           filter(coach != "Jeff Saturday")

wins <- fourth_decisions %>%
  select(team = posteam,
         season, 
         coach) %>%
  arrange(team, season) %>%
  filter(coach != "Jeff Saturday") %>%
  mutate(wins = c(ARI, ATL, BAL, BUF, CAR, CHI, CIN, CLE, DAL, DEN, DET, GB, HOU, IND, JAX, KC, LA, LAC, LV, MIA, MIN, NE, NO, NYG, NYJ, PHI, PIT, SEA, SF, TB, TEN, WAS),
         correct_rate = filtered$should_go)
rm(filtered)

head(wins)
```

```{r}
cross_tab <- wins %>%
  group_by(correct_rate, wins) %>%
  reframe(wins = wins)
head(cross_tab)
tail(cross_tab)
```

